In [3]:
import numpy as np
import pandas as pd
from PIL import Image

In [4]:
annotations_file = 'annotations_split.csv'

In [5]:
anno = pd.read_csv(annotations_file)
anno.head()

                      filename   x1   y1   x2   y2 class Train/Test
0  db_lisa_tiny/sample_001.png  190   40  211   63  stop      Train
1  db_lisa_tiny/sample_002.png    4  246   43  283  stop      Train
2  db_lisa_tiny/sample_003.png  389  286  418  314  stop      Train
3  db_lisa_tiny/sample_004.png  307  243  315  251  stop      Train
4  db_lisa_tiny/sample_005.png  377  249  398  270  stop      Train

In [4]:
# Get filenames from annotations file and get size of each image

width_list = []
height_list = []

filename = []
x1 = []
y1 = []
x2 = []
y2 = []
classes = []


for i in anno["filename"]:
    image = Image.open(i)

    width, height = image.size
    
    if (width!=704):
        width_list.append(width)
        height_list.append(height)

# Insert width and height of images to annotations data frame
anno['width'] = width_list
anno['height'] = height_list

anno.head()

,filename,x1,y1,x2,y2,class,Train/Test,width,height
0,db_lisa_tiny/sample_001.png,190,40,211,63,stop,Train,704,480
1,db_lisa_tiny/sample_002.png,4,246,43,283,stop,Train,704,480
2,db_lisa_tiny/sample_003.png,389,286,418,314,stop,Train,704,480
3,db_lisa_tiny/sample_004.png,307,243,315,251,stop,Train,640,480
4,db_lisa_tiny/sample_005.png,377,249,398,270,stop,Train,640,480

In [6]:
annos = anno[anno['width'] > 650] 
annos

KeyError: 'width'

In [5]:
# Save dataframe as csv file
anno.to_csv("annotations_imSize.csv", index=False)